### PR TITLE
Project setup

### PR DESCRIPTION
**Pull request by kalbek**
On this version of the pull request, the project setup for Webpack and liters has been configured.

### CODE REVIEW

**Review by Naledi-Dikgale — CHANGES_REQUESTED** [review]
Hey @kalbek 
Unfortunately I cannot approve your pull request because it has linters errors,
- Fix linter errors
-  Include a CSS file in your project

**Comment by kalbek** [comment]
Thank you for pointing out that, 🙏 
I'm guessing the CSS file should not be empty initially. Ya ☹️

**Comment by kalbek** [comment]
Do you think I should also include 'modules' folder 📁 , in the src ?

**Comment by Naledi-Dikgale** [comment]
Yes please, include the modules folder

**Pull request merged**
