### PR TITLE
Choose assets for project

### PR DESCRIPTION
**Pull request by kalbek**
On this version of the pull request, assets for the project have been selected and included in the project.

### CODE REVIEW

**Review by Naledi-Dikgale — CHANGES_REQUESTED** [review]
Good job so far, 👏🏽 

## Required changes ♻️ 
- Please consider including font assets
- Please consider placing all your assets in one folder.

**Comment by kalbek** [comment]
😬 Thank you for picking that out. 
- how do you think should I place the font asset inside a folder❓

**Comment by Naledi-Dikgale** [comment]
You can keep the font assets inside the link tag in the head section of the HTML 👍🏽

**Review by Naledi-Dikgale — APPROVED** [review]
Good job! 👏🏽 

There is nothing left to say other than it's time to merge your pull request!

**Pull request merged**
